apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-orchestration-service
  namespace: aicloud-__ENV__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-orchestration-service
  template:
    metadata:
      labels:
        app: ai-orchestration-service
    spec:
      containers:
      - name: ai-orchestration-service
        image: aicloud/ai-orchestration-service:__TAG__
        ports:
        - containerPort: 3005
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: NODE_ENV
        - name: PORT
          value: "3005"
        - name: MONGODB_URI
          value: "mongodb://$(MONGODB_HOST):$(MONGODB_PORT)/aicloud_orchestration"
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: MONGODB_PORT
        - name: REDIS_URL
          value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: REDIS_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: JWT_SECRET
        - name: STORAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: STORAGE_SERVICE_URL
        - name: MIDJOURNEY_API_KEY
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: MIDJOURNEY_API_KEY
        - name: STABLE_DIFFUSION_API_KEY
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: STABLE_DIFFUSION_API_KEY
        - name: KLING_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: KLING_AI_API_KEY
        - name: MMAUDIO_API_KEY
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: MMAUDIO_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
