apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: aicloud-__ENV__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: aicloud/api-gateway:__TAG__
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: NODE_ENV
        - name: PORT
          value: "3001"
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: USER_SERVICE_URL
        - name: STORAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: STORAGE_SERVICE_URL
        - name: LLM_ASSISTANT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: LLM_ASSISTANT_SERVICE_URL
        - name: AI_ORCHESTRATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: AI_ORCHESTRATION_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
