apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: aicloud-__ENV__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
      - name: storage-service
        image: aicloud/storage-service:__TAG__
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: NODE_ENV
        - name: PORT
          value: "3003"
        - name: MONGODB_URI
          value: "mongodb://$(MONGODB_HOST):$(MONGODB_PORT)/aicloud_storage"
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: MONGODB_PORT
        - name: STORAGE_TYPE
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: STORAGE_TYPE
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: S3_ENDPOINT
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: S3_SECRET_KEY
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: aicloud-config
              key: S3_BUCKET
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: storage-data
          mountPath: /app/storage
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: storage-data
        persistentVolumeClaim:
          claimName: storage-pvc
