apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: aicloud
  labels:
    app: storage-service
spec:
  selector:
    app: storage-service
  ports:
    - port: 3002
      targetPort: 3002
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: aicloud
  labels:
    app: storage-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
      - name: storage-service
        image: aicloud/storage-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: aicloud-config
        - secretRef:
            name: aicloud-secrets
        env:
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          value: "mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DB)?authSource=admin"
        - name: S3_ENDPOINT
          value: "http://$(MINIO_HOST):$(MINIO_API_PORT)"
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: MINIO_ROOT_USER
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aicloud-secrets
              key: MINIO_ROOT_PASSWORD
        volumeMounts:
        - name: storage-uploads
          mountPath: /app/uploads
        - name: storage-temp
          mountPath: /app/temp
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
      volumes:
      - name: storage-uploads
        persistentVolumeClaim:
          claimName: storage-uploads-pvc
      - name: storage-temp
        emptyDir: {}