apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-uploads-pvc
  namespace: aicloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard